//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Plugin.SMS.Smsc.SmscService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smsc.ru/sys/soap.php", ConfigurationName="SmscService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (balance) of message get_balanceRequest does not match the default value (get_balance)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.get_balanceResponse get_balance(Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_balanceResponse> get_balanceAsync(Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (send) of message send_smsRequest does not match the default value (send_sms)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.send_smsResponse send_sms(Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.send_smsResponse> send_smsAsync(Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (send2) of message send_sms2Request does not match the default value (send_sms2)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.send_sms2Response send_sms2(Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.send_sms2Response> send_sms2Async(Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request request);
        
        // CODEGEN: Generating message contract since the wrapper name (cost) of message get_sms_costRequest does not match the default value (get_sms_cost)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.get_sms_costResponse get_sms_cost(Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_sms_costResponse> get_sms_costAsync(Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (cost2) of message get_sms_cost2Request does not match the default value (get_sms_cost2)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Response get_sms_cost2(Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Response> get_sms_cost2Async(Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request request);
        
        // CODEGEN: Generating message contract since the wrapper name (status) of message get_statusRequest does not match the default value (get_status)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.get_statusResponse get_status(Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_statusResponse> get_statusAsync(Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (status2) of message get_status2Request does not match the default value (get_status2)
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Nop.Plugin.SMS.Smsc.SmscService.get_status2Response get_status2(Nop.Plugin.SMS.Smsc.SmscService.get_status2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smsc.ru/sys/soap.php", ReplyAction="*")]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_status2Response> get_status2Async(Nop.Plugin.SMS.Smsc.SmscService.get_status2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class BalanceResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string balanceField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class Status2ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string last_dateField;
        
        private string last_timestampField;
        
        private string errField;
        
        private string errorField;
        
        private string send_dateField;
        
        private string send_timestampField;
        
        private string phoneField;
        
        private string costField;
        
        private string sender_idField;
        
        private string status_nameField;
        
        private string messageField;
        
        private string operatorField;
        
        private string regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string last_date {
            get {
                return this.last_dateField;
            }
            set {
                this.last_dateField = value;
                this.RaisePropertyChanged("last_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string last_timestamp {
            get {
                return this.last_timestampField;
            }
            set {
                this.last_timestampField = value;
                this.RaisePropertyChanged("last_timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string err {
            get {
                return this.errField;
            }
            set {
                this.errField = value;
                this.RaisePropertyChanged("err");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string send_date {
            get {
                return this.send_dateField;
            }
            set {
                this.send_dateField = value;
                this.RaisePropertyChanged("send_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string send_timestamp {
            get {
                return this.send_timestampField;
            }
            set {
                this.send_timestampField = value;
                this.RaisePropertyChanged("send_timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sender_id {
            get {
                return this.sender_idField;
            }
            set {
                this.sender_idField = value;
                this.RaisePropertyChanged("sender_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string status_name {
            get {
                return this.status_nameField;
            }
            set {
                this.status_nameField = value;
                this.RaisePropertyChanged("status_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class StatusResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string last_dateField;
        
        private string last_timestampField;
        
        private string errField;
        
        private string errorField;
        
        private string send_dateField;
        
        private string send_timestampField;
        
        private string phoneField;
        
        private string costField;
        
        private string sender_idField;
        
        private string status_nameField;
        
        private string messageField;
        
        private string operatorField;
        
        private string regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string last_date {
            get {
                return this.last_dateField;
            }
            set {
                this.last_dateField = value;
                this.RaisePropertyChanged("last_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string last_timestamp {
            get {
                return this.last_timestampField;
            }
            set {
                this.last_timestampField = value;
                this.RaisePropertyChanged("last_timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string err {
            get {
                return this.errField;
            }
            set {
                this.errField = value;
                this.RaisePropertyChanged("err");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string send_date {
            get {
                return this.send_dateField;
            }
            set {
                this.send_dateField = value;
                this.RaisePropertyChanged("send_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string send_timestamp {
            get {
                return this.send_timestampField;
            }
            set {
                this.send_timestampField = value;
                this.RaisePropertyChanged("send_timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sender_id {
            get {
                return this.sender_idField;
            }
            set {
                this.sender_idField = value;
                this.RaisePropertyChanged("sender_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string status_name {
            get {
                return this.status_nameField;
            }
            set {
                this.status_nameField = value;
                this.RaisePropertyChanged("status_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class Cost2ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string costField;
        
        private string cntField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
                this.RaisePropertyChanged("cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class CostResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string costField;
        
        private string cntField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
                this.RaisePropertyChanged("cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class Send2ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string balanceField;
        
        private string costField;
        
        private string cntField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
                this.RaisePropertyChanged("cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smsc.ru/sys/soap.php")]
    public partial class SendResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string balanceField;
        
        private string costField;
        
        private string cntField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
                this.RaisePropertyChanged("cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="balance", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_balanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        public get_balanceRequest() {
        }
        
        public get_balanceRequest(string login, string psw) {
            this.login = login;
            this.psw = psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceResponse", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_balanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.BalanceResponseType balanceresult;
        
        public get_balanceResponse() {
        }
        
        public get_balanceResponse(Nop.Plugin.SMS.Smsc.SmscService.BalanceResponseType balanceresult) {
            this.balanceresult = balanceresult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class send_smsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phones;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string time;
        
        public send_smsRequest() {
        }
        
        public send_smsRequest(string login, string psw, string phones, string mes, string id, string sender, string time) {
            this.login = login;
            this.psw = psw;
            this.phones = phones;
            this.mes = mes;
            this.id = id;
            this.sender = sender;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendResponse", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class send_smsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.SendResponseType sendresult;
        
        public send_smsResponse() {
        }
        
        public send_smsResponse(Nop.Plugin.SMS.Smsc.SmscService.SendResponseType sendresult) {
            this.sendresult = sendresult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send2", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class send_sms2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phones;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string query;
        
        public send_sms2Request() {
        }
        
        public send_sms2Request(string login, string psw, string phones, string mes, string id, string sender, string time, string query) {
            this.login = login;
            this.psw = psw;
            this.phones = phones;
            this.mes = mes;
            this.id = id;
            this.sender = sender;
            this.time = time;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send2Response", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class send_sms2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.Send2ResponseType sendresult;
        
        public send_sms2Response() {
        }
        
        public send_sms2Response(Nop.Plugin.SMS.Smsc.SmscService.Send2ResponseType sendresult) {
            this.sendresult = sendresult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cost", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_sms_costRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phones;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mes;
        
        public get_sms_costRequest() {
        }
        
        public get_sms_costRequest(string login, string psw, string phones, string mes) {
            this.login = login;
            this.psw = psw;
            this.phones = phones;
            this.mes = mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CostResponse", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_sms_costResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.CostResponseType costresult;
        
        public get_sms_costResponse() {
        }
        
        public get_sms_costResponse(Nop.Plugin.SMS.Smsc.SmscService.CostResponseType costresult) {
            this.costresult = costresult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cost2", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_sms_cost2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phones;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string query;
        
        public get_sms_cost2Request() {
        }
        
        public get_sms_cost2Request(string login, string psw, string phones, string mes, string query) {
            this.login = login;
            this.psw = psw;
            this.phones = phones;
            this.mes = mes;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cost2Response", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_sms_cost2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.Cost2ResponseType costresult;
        
        public get_sms_cost2Response() {
        }
        
        public get_sms_cost2Response(Nop.Plugin.SMS.Smsc.SmscService.Cost2ResponseType costresult) {
            this.costresult = costresult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="status", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_statusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string all;
        
        public get_statusRequest() {
        }
        
        public get_statusRequest(string login, string psw, string phone, string id, string all) {
            this.login = login;
            this.psw = psw;
            this.phone = phone;
            this.id = id;
            this.all = all;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusResponse", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_statusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.StatusResponseType statusresult;
        
        public get_statusResponse() {
        }
        
        public get_statusResponse(Nop.Plugin.SMS.Smsc.SmscService.StatusResponseType statusresult) {
            this.statusresult = statusresult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="status2", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_status2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string all;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string query;
        
        public get_status2Request() {
        }
        
        public get_status2Request(string login, string psw, string phone, string id, string all, string query) {
            this.login = login;
            this.psw = psw;
            this.phone = phone;
            this.id = id;
            this.all = all;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Status2Response", WrapperNamespace="http://smsc.ru/sys/soap.php", IsWrapped=true)]
    public partial class get_status2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smsc.ru/sys/soap.php", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nop.Plugin.SMS.Smsc.SmscService.Status2ResponseType statusresult;
        
        public get_status2Response() {
        }
        
        public get_status2Response(Nop.Plugin.SMS.Smsc.SmscService.Status2ResponseType statusresult) {
            this.statusresult = statusresult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap>, Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.get_balanceResponse Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_balance(Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest request) {
            return base.Channel.get_balance(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.BalanceResponseType get_balance(string login, string psw) {
            Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest();
            inValue.login = login;
            inValue.psw = psw;
            Nop.Plugin.SMS.Smsc.SmscService.get_balanceResponse retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_balance(inValue);
            return retVal.balanceresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_balanceResponse> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_balanceAsync(Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest request) {
            return base.Channel.get_balanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_balanceResponse> get_balanceAsync(string login, string psw) {
            Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_balanceRequest();
            inValue.login = login;
            inValue.psw = psw;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_balanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.send_smsResponse Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.send_sms(Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest request) {
            return base.Channel.send_sms(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.SendResponseType send_sms(string login, string psw, string phones, string mes, string id, string sender, string time) {
            Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            inValue.id = id;
            inValue.sender = sender;
            inValue.time = time;
            Nop.Plugin.SMS.Smsc.SmscService.send_smsResponse retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).send_sms(inValue);
            return retVal.sendresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.send_smsResponse> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.send_smsAsync(Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest request) {
            return base.Channel.send_smsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.send_smsResponse> send_smsAsync(string login, string psw, string phones, string mes, string id, string sender, string time) {
            Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.send_smsRequest();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            inValue.id = id;
            inValue.sender = sender;
            inValue.time = time;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).send_smsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.send_sms2Response Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.send_sms2(Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request request) {
            return base.Channel.send_sms2(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.Send2ResponseType send_sms2(string login, string psw, string phones, string mes, string id, string sender, string time, string query) {
            Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request inValue = new Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            inValue.id = id;
            inValue.sender = sender;
            inValue.time = time;
            inValue.query = query;
            Nop.Plugin.SMS.Smsc.SmscService.send_sms2Response retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).send_sms2(inValue);
            return retVal.sendresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.send_sms2Response> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.send_sms2Async(Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request request) {
            return base.Channel.send_sms2Async(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.send_sms2Response> send_sms2Async(string login, string psw, string phones, string mes, string id, string sender, string time, string query) {
            Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request inValue = new Nop.Plugin.SMS.Smsc.SmscService.send_sms2Request();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            inValue.id = id;
            inValue.sender = sender;
            inValue.time = time;
            inValue.query = query;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).send_sms2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.get_sms_costResponse Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_sms_cost(Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest request) {
            return base.Channel.get_sms_cost(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.CostResponseType get_sms_cost(string login, string psw, string phones, string mes) {
            Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            Nop.Plugin.SMS.Smsc.SmscService.get_sms_costResponse retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_sms_cost(inValue);
            return retVal.costresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_sms_costResponse> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_sms_costAsync(Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest request) {
            return base.Channel.get_sms_costAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_sms_costResponse> get_sms_costAsync(string login, string psw, string phones, string mes) {
            Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_sms_costRequest();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_sms_costAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Response Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_sms_cost2(Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request request) {
            return base.Channel.get_sms_cost2(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.Cost2ResponseType get_sms_cost2(string login, string psw, string phones, string mes, string query) {
            Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            inValue.query = query;
            Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Response retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_sms_cost2(inValue);
            return retVal.costresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Response> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_sms_cost2Async(Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request request) {
            return base.Channel.get_sms_cost2Async(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Response> get_sms_cost2Async(string login, string psw, string phones, string mes, string query) {
            Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_sms_cost2Request();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phones = phones;
            inValue.mes = mes;
            inValue.query = query;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_sms_cost2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.get_statusResponse Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_status(Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest request) {
            return base.Channel.get_status(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.StatusResponseType get_status(string login, string psw, string phone, string id, string all) {
            Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phone = phone;
            inValue.id = id;
            inValue.all = all;
            Nop.Plugin.SMS.Smsc.SmscService.get_statusResponse retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_status(inValue);
            return retVal.statusresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_statusResponse> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_statusAsync(Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest request) {
            return base.Channel.get_statusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_statusResponse> get_statusAsync(string login, string psw, string phone, string id, string all) {
            Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_statusRequest();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phone = phone;
            inValue.id = id;
            inValue.all = all;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_statusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Nop.Plugin.SMS.Smsc.SmscService.get_status2Response Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_status2(Nop.Plugin.SMS.Smsc.SmscService.get_status2Request request) {
            return base.Channel.get_status2(request);
        }
        
        public Nop.Plugin.SMS.Smsc.SmscService.Status2ResponseType get_status2(string login, string psw, string phone, string id, string all, string query) {
            Nop.Plugin.SMS.Smsc.SmscService.get_status2Request inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_status2Request();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phone = phone;
            inValue.id = id;
            inValue.all = all;
            inValue.query = query;
            Nop.Plugin.SMS.Smsc.SmscService.get_status2Response retVal = ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_status2(inValue);
            return retVal.statusresult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_status2Response> Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap.get_status2Async(Nop.Plugin.SMS.Smsc.SmscService.get_status2Request request) {
            return base.Channel.get_status2Async(request);
        }
        
        public System.Threading.Tasks.Task<Nop.Plugin.SMS.Smsc.SmscService.get_status2Response> get_status2Async(string login, string psw, string phone, string id, string all, string query) {
            Nop.Plugin.SMS.Smsc.SmscService.get_status2Request inValue = new Nop.Plugin.SMS.Smsc.SmscService.get_status2Request();
            inValue.login = login;
            inValue.psw = psw;
            inValue.phone = phone;
            inValue.id = id;
            inValue.all = all;
            inValue.query = query;
            return ((Nop.Plugin.SMS.Smsc.SmscService.ServiceSoap)(this)).get_status2Async(inValue);
        }
    }
}
